set nocompatible              " be iMproved, required
filetype off                  " required

" Force vim to load local vimrc if present
set exrc
" Restrict commands allowed in local vim, disallowing commands that write to
" file or execute shell commands
" set secure

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" Code snippets

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
"
Plugin 'junegunn/fzf'
Plugin 'w0rp/ale'
Plugin 'itchyny/lightline.vim'

" NERDTree
Plugin 'scrooloose/nerdtree'
Plugin 'flazz/vim-colorschemes'
Plugin 'christoomey/vim-tmux-navigator'

" Python PEP8
Plugin 'nvie/vim-flake8'

Plugin 'jpo/vim-railscasts-theme'

" Let's do some Go baby
"Plugin 'fatih/vim-go'

" Autocomplete for C-Family Languages
Plugin 'Valloric/YouCompleteMe'
"Generate config for YCM
Plugin 'rdnetto/YCM-Generator'

"Display object tags
Plugin 'majutsushi/tagbar'

" Javascript/Node Stuff
Plugin 'pangloss/vim-javascript'
Plugin 'moll/vim-node'
Plugin 'mxw/vim-jsx'
Plugin 'othree/javascript-libraries-syntax.vim'
Plugin 'vasconcelloslf/vim-interestingwords'

" Vim Surround
Plugin 'tpope/vim-surround'

" handlebars support
Plugin 'mustache/vim-mustache-handlebars'

" Polyglot
Plugin 'sheerun/vim-polyglot'

" All of your Plugins must be added before the following line
call vundle#end()            " required


filetype on
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" Open NERDTree with Ctrl+n
map <C-n> :NERDTreeToggle<CR>

" Toggle Tagbar with Ctrl+t
map <C-t> :TagbarToggle<CR>


" disable arrows, let's see how long this lasts
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>


" auto-load vimrc after saving
au BufWritePost .vimrc so $MYVIMRC

nnoremap Q <nop>

set shell=/bin/zsh
set incsearch
set ignorecase
set smartcase
set scrolloff=0
set autoindent
set shiftround

"C-c send enter in insert mode
inoremap <C-c> <Esc>

set number
hi Normal ctermbg=NONE

" Mouse, finally!
:set mouse=a

colorscheme Monokai
set ts=4
set expandtab
set copyindent
set shiftwidth=4
set showmatch
set smarttab
set hlsearch
set history=1000
set undolevels=1000
set wildignore=*.swp,*.bak,*.pyc,*.class
set title
set visualbell
set noerrorbells
let python_highlight_all = 1

" turn on syntax highlighting
syntax on
syntax sync fromstart
set autoread
:tnoremap <Esc> <C-\><C-n>
let $PATH = '/usr/local/bin:'.$PATH
let g:ycm_python_binary_path = 'python'
let g:python3_host_prog = '/usr/local/bin/python3'

set backspace =indent,eol,start " Make backspace work as it should
set splitright
set splitbelow
set cursorline
set wrapscan

nnoremap <silent> vv <C-w>v
nnoremap <C-t> :tabnew<CR>
nnoremap <C-s> :terminal<CR>

let g:lightline = {
    \ 'colorscheme': 'wombat',
    \ }
